### ISSUE TITLE
llama_decor

### ISSUE THREAD

**Issue by chengzzi89** [chengzzi89/PaperCutOut#27]
![decor_black](https://user-images.githubusercontent.com/28303754/52366826-a17f4400-2a85-11e9-9c44-7b953085ecc8.png)![decor_blue](https://user-images.githubusercontent.com/28303754/52366845-aba14280-2a85-11e9-85c6-64328f72a944.png)![decor_brown](https://user-images.githubusercontent.com/28303754/52366862-b4921400-2a85-11e9-85a2-9873f05ad139.png)![decor_cyan](https://user-images.githubusercontent.com/28303754/52366931-d7bcc380-2a85-11e9-814a-d1fc4a54b06b.png)![decor_gray](https://user-images.githubusercontent.com/28303754/52366939-ddb2a480-2a85-11e9-96c2-0d0ed7646314.png)![decor_green](https://user-images.githubusercontent.com/28303754/52366950-e4d9b280-2a85-11e9-89dd-de48ce9ed40e.png)![decor_light_blue](https://user-images.githubusercontent.com/28303754/52366960-ec00c080-2a85-11e9-9996-9fca05ce13b4.png)![decor_lime](https://user-images.githubusercontent.com/28303754/52366968-f15e0b00-2a85-11e9-8da7-8aac7b8f465b.png)
![decor_magenta](https://user-images.githubusercontent.com/28303754/52367112-4863e000-2a86-11e9-9756-1da3b049ff9f.png)![decor_orange](https://user-images.githubusercontent.com/28303754/52367125-4e59c100-2a86-11e9-9117-f262433db2e2.png)![decor_pink](https://user-images.githubusercontent.com/28303754/52367132-544fa200-2a86-11e9-8e17-95804eb11d82.png)![decor_purple](https://user-images.githubusercontent.com/28303754/52367144-59acec80-2a86-11e9-8512-d2e818b6bdba.png)![decor_red](https://user-images.githubusercontent.com/28303754/52367157-629dbe00-2a86-11e9-91af-0ab25ea7f367.png)![decor_silver](https://user-images.githubusercontent.com/28303754/52367175-6df0e980-2a86-11e9-917a-7f9934b3dd1b.png)![decor_white](https://user-images.githubusercontent.com/28303754/52367190-76492480-2a86-11e9-8027-a6a42a757dbb.png)![decor_yellow](https://user-images.githubusercontent.com/28303754/52367210-7cd79c00-2a86-11e9-9002-004a8d1d782d.png)

**Comment by AngelMexYT** [comment]
I like the colors, but I feel that it lacks a bit of decoration, I should look more like the rugs.

**Comment by chengzzi89** [comment]
@AngelMexYT Yes, it is a bit single!
