### ISSUE TITLE
Missing alternate textures?

### ISSUE THREAD

**Issue by francisyzy** [chengzzi89/PaperCutOut#54]
Game Version 1.15.2

Vanilla + Paper Cut Out
![2020-03-30_21 22 50](https://user-images.githubusercontent.com/24467184/77917214-dde6b280-72cc-11ea-90f7-b79565836450.png)
Vanilla Texture Pack
![2020-03-30_21 25 52](https://user-images.githubusercontent.com/24467184/77917391-1a1a1300-72cd-11ea-9f01-4c5e7daa966a.png)
Optifine (alternate blocks off) + Paper Cut Out
![2020-03-30_21 29 00](https://user-images.githubusercontent.com/24467184/77917904-b6441a00-72cd-11ea-9e1c-721a8aac4b47.png)

**Comment by chengzzi89** [comment]
The problem of stone texture losing texture in random blocks, there is currently no best way!  So I re-uploaded the version with the blockstates folder removed!  I hope you can feel at ease!
