### ISSUE TITLE
Can't use the texture pack!!!

### ISSUE THREAD

**Issue by maththehuman** [chengzzi89/PaperCutOut#66]
I simply can not play with the paper cut out texture pack on my phone, I'm using the right bedrock version of the pack, version 1.16, just like the game version. When I activate the pack in my world and then tap to play, the texture pack is not there, in the info looks like the pack is corrupted, having just 1MB and thumb glitched. I'm very frustrated cuz it's just on my phone, I tried to use the pack on my tablet com it's normal, working. Somebody please!

**Comment by chengzzi89** [comment]
It may be because of my occasional negligence that some data has bugs, but I will try my best to continue to optimize!
