### ISSUE TITLE
[1.16] Hanging lanterns are big purple and black blocks

### ISSUE THREAD

**Issue by benrchg** [chengzzi89/PaperCutOut#67]
![image](https://user-images.githubusercontent.com/60044535/90550786-b1a2d400-e190-11ea-8577-4ec28f05182b.png)

**Comment by benrchg** [comment]
As the texture blocks/hanging_lantern does not exist, the lantern.json in blockstate is causing the problem. I deleted it for my instance of the texture pack and it's working fine.

**Comment by chengzzi89** [comment]
Sorry I just saw it now, your feedback may have been fixed by me!

**Comment by benrchg** [comment]
No problem aha
I have been a huge fan on this texture pack for years now and it feels great that someone continued it !
To be honest, I fixed a bunch of things for the 1.16.2 version because I really wanted to use it. I added the brute texture for example. If you like the texture, I can definitely send you the png ;)
![2020-09-18_12 32 33](https://user-images.githubusercontent.com/60044535/93588098-3577f800-f9ab-11ea-8e20-99dbac31bb07.png)
![2020-09-18_12 32 45](https://user-images.githubusercontent.com/60044535/93588108-390b7f00-f9ab-11ea-94d0-ddd49ecee8d7.png)

**Comment by chengzzi89** [comment]
> 没问题，啊哈
> ，多年来我一直是这个纹理包的忠实粉丝，有人继续使用它真是太好了！
> 老实说，我修复了1.16.2版本的很多问题，因为我真的很想使用它。例如，我添加了粗糙的纹理。如果您喜欢纹理，我绝对可以向您发送png;）
> ![2020-09-18_12 32 33](https://user-images.githubusercontent.com/60044535/93588098-3577f800-f9ab-11ea-8e20-99dbac31bb07.png)
> ![2020-09-18_12 32 45](https://user-images.githubusercontent.com/60044535/93588108-390b7f00-f9ab-11ea-94d0-ddd49ecee8d7.png)

https://github.com/chengzzi89/PaperCutOut/issues/45#issuecomment-694746358
