### ISSUE TITLE
［1.14］More synthesis stations

### ISSUE THREAD

**Issue by chengzzi89** [chengzzi89/PaperCutOut#9]
cartography
![crafting_table_top](https://user-images.githubusercontent.com/28303754/52351210-3aea2e00-2a65-11e9-9d49-782cc9bb35af.png)![cartography_table_side1](https://user-images.githubusercontent.com/28303754/52349284-33288a80-2a61-11e9-84bf-3e71b0d6cfcf.png)![cartography_table_side2](https://user-images.githubusercontent.com/28303754/56341084-8861e480-61e6-11e9-80f6-298f3fdc10d2.png)

fletcher
![crafting_table_top](https://user-images.githubusercontent.com/28303754/52351210-3aea2e00-2a65-11e9-9d49-782cc9bb35af.png)![fletcher_table_side1](https://user-images.githubusercontent.com/28303754/52349473-99ada880-2a61-11e9-8f71-55bb58337cc2.png)![fletcher_table_side2](https://user-images.githubusercontent.com/28303754/56341114-9f083b80-61e6-11e9-9d1e-7e2d95ddea86.png)
![cartography_table](https://user-images.githubusercontent.com/28303754/52361959-69becf00-2a7a-11e9-994c-cfcee4ef4ec1.png)

smithing
![crafting_table_top](https://user-images.githubusercontent.com/28303754/52351210-3aea2e00-2a65-11e9-9d49-782cc9bb35af.png)![crafting_table_front](https://user-images.githubusercontent.com/28303754/52351164-1b530580-2a65-11e9-82e8-ac10053cd1d9.png)![smithing_table_bottom](https://user-images.githubusercontent.com/28303754/52351177-25750400-2a65-11e9-96e1-d8b20314fee8.png)![smithing_table_side](https://user-images.githubusercontent.com/28303754/56341134-ac252a80-61e6-11e9-92aa-75fc77fb9657.png)

**Comment by AngelMexYT** [comment]
I like the GUI, but the model of the Item still does not convince me. I think it looks like a 1x1 texture
